# -*- coding: utf-8 -*-
"""Brest Canser Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmBmkCDkJEGVQhnrU4c_Dzxsmm4aXS-6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets
from sklearn.model_selection import train_test_split

breast_cancer_data = sklearn.datasets.load_breast_cancer()

print(breast_cancer_data)

df = pd.read_csv("/content/breast_cancer_dataset_new.csv")

df

df.head()

df['label']=breast_cancer_data.target

df.tail()

df.shape

df.info()

df.isnull().sum()

df.describe()

df['label'].value_counts()

df.groupby('label').mean(numeric_only=True)

X = df.drop(columns=["label", "diagnosis"],axis=1)
Y = df["label"]

print(X)

print(Y)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape, X_train.shape, X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

print(X_train_std)

"""Building the Neural Network"""

import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

model=keras.Sequential([
                         keras.layers.Flatten(input_shape=(30,)),
                         keras.layers.Dense(20,activation='relu'),
                         keras.layers.Dense(2,activation='sigmoid')

])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, Y_train,validation_split=0.1,epochs=10)

"""Visualizing accuracy and loss"""

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('model.accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')

plt.legend(['training data','validation data'],loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')

plt.legend(['training data','validation data'], loc = 'lower right')

loss = accuracy = model.evaluate(X_test_std,Y_test)
print(accuracy)

print(X_test_std.shape)
print(X_test_std[0])

Y_pred = model.predict(X_test_std)

print(Y_pred.shape)
print(Y_pred[0])

print(X_test)

print(Y_pred)

print(X_test_std)

my_list = [10,20,30]

index_of_max_value = np.argmax(my_list)
print(my_list)
print(index_of_max_value)

Y_pred_labels = [np.argmax(i) for i in Y_pred]
print(Y_pred_labels)

"""Building the predictive system"""

input_data = (17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.3563, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189)

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

input_data_std = scaler.transform(input_data_reshaped)

prediction = model.predict(input_data_std)
print(prediction)

prediction_label = [np.argmax(prediction)]
print(prediction_label)

if(prediction_label[0]==0):
  print('The tumor is Malignant')

else:
  print('The tumor is benign')

